const express = require("express");
const router = express.Router();
const Authenticate = require("../middleware/AuthMiddleware");
const orderController = require('../controller/OrderController');
router.post('/order/create-order', Authenticate.authenticateToken,orderController.createOrder);
router.get('/order/order-user', Authenticate.authenticateToken,orderController.getOrdersByUser);
router.get('/order/order-user', Authenticate.authenticateToken,orderController.getOrdersByUser);
router.put('/approveOrder/:id', Authenticate.authenticateToken,orderController.approveOrder);
router.get('/order/order-seller', Authenticate.authenticateToken,orderController.getOrdersBySeller);
router.get('/order/order-detail-seller/:id', Authenticate.authenticateToken,orderController.getOrdersByDetailSeller);
module.exports = router;